### ISSUE TITLE
Translation issue while reading numeric values

### ISSUE THREAD

**Issue by dk3775** [swapagarwal/geeksay#389]
While we enter a numeric value with "," we are getting the answer as 0 but we should get either original string or the translated word.

**Comment by sky-akash05** [comment]
hi, I will love to contribute to your project . Will feel grateful i you can assign this to me,

**Comment by rakshitdabral** [comment]
Hope this is what you wanted as the fix for the issue, currently works wells and every other feature is working pretty well too attaching few screenshot so you can verify what the fix is about mainly 

if we enter bare numerical value it gets converted into binary form and if we add any extra character next to it, it gets converted into normal string

![Screenshot (5)](https://user-images.githubusercontent.com/96056758/193602412-99f17c42-078f-431e-8bb5-55fc07c88392.png)
![Screenshot (3)](https://user-images.githubusercontent.com/96056758/193602417-a49079a5-1694-4dc6-8a5f-8d9575adb0ed.png)
![Screenshot (4)](https://user-images.githubusercontent.com/96056758/193602424-4639898a-518c-4429-ba7f-027b925d817b.png)

**Comment by rakshitdabral** [comment]
#391

**Comment by dk3775** [comment]
@rakshitdabral 's PR #391 Solves this issue perfectly.
So closing this issue.
